- name: install dependencies
  apt: name={{ item }} update_cache=yes cache_valid_time=86400
  with_items:
      - python-httplib2

- name: get statsd
  git: repo=https://github.com/bitly/statsdaemon.git dest=/root/statsdaemon

- name: install golang
  apt: name=golang-go

- name: get github.com/stretchr/testify/assert
  shell: GOPATH=/root/gopath go get github.com/stretchr/testify/assert

- name: compile statsd
  shell: cd /root/statsdaemon && GOPATH=/root/gopath ./dist.sh creates=/root/statsdaemon/dist/statsdaemon-0.7.1.linux-amd64.go1.6.2.tar.gz

- name: get statsd
  unarchive: src=/root/statsdaemon/dist/statsdaemon-0.7.1.linux-amd64.go1.6.2.tar.gz
            dest=/root copy=no creates=/root/statsdaemon-0.7.1.linux-amd64.go1.6.2 list_files=yes
  ignore_errors: true
  register: result

- name: move /root/statsdaemon-0.7.1.linux-amd64.go1.6.2/statsdaemon to /usr/local/bin
  shell: mv -v /root/statsdaemon-0.7.1.linux-amd64.go1.6.2/statsdaemon /usr/local/bin/statsdaemon
  when: result.changed

- name: create statsd user
  user: name=statsd

- name: put systemd unit file
  template: src=statsd.service dest=/etc/systemd/system/statsd.service backup=yes
  notify: systemctl daemon-reload

- name: enable statsd service
  service: name=statsd state=started enabled=yes
